AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cause information to be written to DLQ
Resources:
  inputBucket:
    Type: AWS::S3::Bucket
  snsHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: snsHandler
      Description: Handle SNS notifications of DLQ entries
      Handler: sns_handler.handler
      Runtime: python2.7
      CodeUri: '.'
      Timeout: 10
      MemorySize: 128
      Policies:
        - AWSLambdaExecute
  dlqSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint: !GetAtt snsHandlerFunction.Arn
        Protocol: lambda
  longRunningFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: longRunner
      Description: Just sleep and write to a DLQ
      Handler: index.handler
      Runtime: python2.7
      CodeUri: '.'
      Timeout: 3
      MemorySize: 256
      DeadLetterQueue:
        Type: SNS
        TargetArn: !Ref dlqSnsTopic
      Policies:
        - AWSLambdaExecute # Managed Policy
        - SNSPublishMessagePolicy:
            TopicName: !Ref dlqSnsTopic
      Events:
        inputBucket:
          Type: S3
          Properties:
            Bucket: !Ref inputBucket
            Events: s3:ObjectCreated:*
