AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Take S3 object and insert to DynamoDB
Resources:
  InputBucket:
    Type: AWS::S3::Bucket
  StockPricesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: stock-prices-s3ToDynamo
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  s3ToDynamo:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: s3ToDynamo
      Description: Take S3 object and insert to DynamoDB
      Handler: index.handler
      Runtime: python2.7
      CodeUri: '.'
      Timeout: 10
      MemorySize: 256
      Environment:
        Variables:
          DYNAMO_TABLE: stock-prices-s3ToDynamo
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: 'arn:aws:s3:::*'
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:putItem
              Resource:
                Fn::Join:
                  - ''
                  - - "arn:aws:dynamodb:"
                    - Ref: "AWS::Region"
                    - ":"
                    - Ref: "AWS::AccountId"
                    - ":table/stock-prices-s3ToDynamo"

      Events:
        ReportUpload:
          Type: S3
          Properties:
            Bucket: !Ref InputBucket
            Events: s3:ObjectCreated:*
